# Generated by Django 5.2.6 on 2026-07-27 15:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramsubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrow',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'Секцию «Выберите своё»', 'verbose_name_plural': 'Выберите своё'},
        ),
        migrations.AddField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.advantage_image_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt'),
        ),
    ]
