# Generated by Django 5.2.6 on 2026-07-27 16:32

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productrow_options_advantage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Антиспам-поле'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='advantages_eyebrow',
            field=models.CharField(default='Подход', max_length=255, verbose_name='Подзаголовок секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='advantages_title_emphasis',
            field=models.CharField(default='нас', max_length=255, verbose_name='Акцент заголовка секции преимуществ'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='advantages_title_part1',
            field=models.CharField(default='Почему выбирают', max_length=255, verbose_name='Заголовок секции преимуществ, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_button_label',
            field=models.CharField(default='Оставить заявку', max_length=120, verbose_name='Текст кнопки призыва к действию'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_eyebrow',
            field=models.CharField(default='Давайте начнём', max_length=255, verbose_name='Подзаголовок призыва к действию'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_text',
            field=models.TextField(default='Оставьте заявку, и мы поможем подобрать формат, материалы и стиль.', verbose_name='Текст призыва к действию'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_title_emphasis',
            field=models.CharField(default='превратим её в красивый результат', max_length=255, verbose_name='Акцент заголовка призыва к действию'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_title_part1',
            field=models.CharField(default='Расскажите о своей идее —', max_length=255, verbose_name='Заголовок призыва к действию, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='form_submit_label',
            field=models.CharField(default='Отправить заявку', max_length=120, verbose_name='Текст кнопки отправки формы'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='form_text',
            field=models.TextField(default='Расскажите о задаче — ответим и поможем определиться с форматом.', verbose_name='Текст формы'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='form_title',
            field=models.CharField(default='Оставить заявку', max_length=255, verbose_name='Заголовок формы'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_button_label',
            field=models.CharField(default='Создать подарок', max_length=120, verbose_name='Текст кнопки секции подарка'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_eyebrow',
            field=models.CharField(default='Подарить момент', max_length=255, verbose_name='Подзаголовок секции подарка'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home_image_upload_to, verbose_name='Изображение подарка'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения подарка'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_text',
            field=models.TextField(default='Соберём персональный подарок под событие, настроение и человека.', verbose_name='Текст секции подарка'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_title_emphasis',
            field=models.CharField(default='момент', max_length=255, verbose_name='Акцент заголовка секции подарка'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='gift_title_part1',
            field=models.CharField(default='Подарить', max_length=255, verbose_name='Заголовок секции подарка, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_book_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения книги'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_book_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home_image_upload_to, verbose_name='Изображение книги'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_button_label',
            field=models.CharField(default='Оставить заявку', max_length=120, verbose_name='Текст кнопки первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_calendar_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения календаря'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_calendar_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home_image_upload_to, verbose_name='Изображение календаря'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_channel_label',
            field=models.CharField(default='Канал в MAX', max_length=120, verbose_name='Текст ссылки на канал'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_diploma_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения диплома'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_diploma_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home_image_upload_to, verbose_name='Изображение диплома'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_eyebrow',
            field=models.CharField(default='Дизайн и печать', max_length=255, verbose_name='Подзаголовок первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_footnote',
            field=models.CharField(default='Маленькая деталь — большое впечатление', max_length=255, verbose_name='Подпись первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_lead',
            field=models.TextField(default='Дизайн, печать и персональные подарки — с вниманием к каждой детали.', verbose_name='Описание первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_planner_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения планера'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_planner_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home_image_upload_to, verbose_name='Изображение планера'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_secondary_label',
            field=models.CharField(default='Смотреть услуги', max_length=120, verbose_name='Текст дополнительной ссылки первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title_emphasis',
            field=models.CharField(default='в руках', max_length=255, verbose_name='Акцент в заголовке первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title_part1',
            field=models.CharField(default='Идеи, которые', max_length=255, verbose_name='Заголовок первого экрана, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title_part2',
            field=models.CharField(default='можно держать', max_length=255, verbose_name='Заголовок первого экрана, часть 2'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='products_eyebrow',
            field=models.CharField(default='Материалы и детали', max_length=255, verbose_name='Подзаголовок секции материалов'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='products_intro',
            field=models.TextField(default='Здесь — не краткий перечень услуг, а детали каждого изделия: материалы, форматы и возможности персонализации. Так выбрать своё проще.', verbose_name='Описание секции материалов'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='products_title_emphasis',
            field=models.CharField(default='рассматривать', max_length=255, verbose_name='Акцент заголовка секции материалов'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='products_title_part1',
            field=models.CharField(default='То, что хочется', max_length=255, verbose_name='Заголовок секции материалов, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Поисковое описание'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поисковый заголовок'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_eyebrow',
            field=models.CharField(default='Выберите своё', max_length=255, verbose_name='Подзаголовок секции услуг'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_intro',
            field=models.TextField(default='Собираем дизайн и печать в целый, живой результат — от первого эскиза до готового изделия.', verbose_name='Описание секции услуг'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_title_emphasis',
            field=models.CharField(default='забота', max_length=255, verbose_name='Акцент заголовка секции услуг'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_title_part1',
            field=models.CharField(default='Услуги, в которых', max_length=255, verbose_name='Заголовок секции услуг, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='services_title_part2',
            field=models.CharField(default='видна', max_length=255, verbose_name='Заголовок секции услуг, часть 2'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='steps_eyebrow',
            field=models.CharField(default='Просто и прозрачно', max_length=255, verbose_name='Подзаголовок секции шагов'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='steps_text',
            field=models.TextField(default='От первой идеи до момента, когда результат уже у вас в руках.', verbose_name='Описание секции шагов'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='steps_title_emphasis',
            field=models.CharField(default='заказать', max_length=255, verbose_name='Акцент заголовка секции шагов'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='steps_title_part1',
            field=models.CharField(default='Как', max_length=255, verbose_name='Заголовок секции шагов, часть 1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='success_text',
            field=models.TextField(default='Заявка отправлена. Мы скоро свяжемся с вами.', verbose_name='Текст сообщения об успехе'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='success_title',
            field=models.CharField(default='Спасибо!', max_length=255, verbose_name='Заголовок сообщения об успехе'),
        ),
        migrations.AlterField(
            model_name='productrow',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание изображения'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='application_email',
            field=models.EmailField(blank=True, default='info@tdp.ru', max_length=254, verbose_name='Электронная почта для заявок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='info@tdp.ru', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'svg'])], verbose_name='Иконка сайта (favicon)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='max_url',
            field=models.CharField(blank=True, default='https://max.ru/channel_TDP', max_length=255, verbose_name='Ссылка на MAX'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.CharField(blank=True, default='tg://resolve?phone=79778071155', max_length=255, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='chat_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='ID чата Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
